version: "3.8"
services:
  kube_host:
    build: .
    container_name: kube_host
    volumes:
      - ./export:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
